services:
  - type: web
    name: travel-planner-ai
    runtime: python
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: GEMINI_API_KEY
        scope: run
        sync: false
